### ISSUE TITLE
KILL Statements are giving exception when there is 0 row returned.

### ISSUE THREAD

**Issue by ahmeturun** [DarkWanderer/ClickHouse.Client#58]
Using 'KILL QUERY' statement and trying to read the results gives error when the result returns 0 row. pls check the example I attached.
[clickhouse-session-locked.zip](https://github.com/DarkWanderer/ClickHouse.Client/files/5729607/clickhouse-session-locked.zip)

**Comment by DarkWanderer** [comment]
Hi. You need to use `ExecuteStatement` rather than `ExecuteReader`/`ExecuteQuery` for DDL and 'administrative' statements (`KILL`/`OPTIMIZE`/`ALTER`/`CREATE`/`DROP` etc.) - the fact that they do return something sometimes is more of an exception than a rule. However, it still should not throw, I'll look into it.

**Comment by DarkWanderer** [comment]
Will be released in next patch
