### ISSUE TITLE
Cast exception for GetInt64 method

### ISSUE THREAD

**Issue by YPermitin** [DarkWanderer/ClickHouse.Client#63]
Доброго дня!

Обнаружил непредвиденное поведение метода "GetInt64" в последней выпущенной на данный момент версии.

Например, есть запрос:
```sql
SELECT
	COUNT(*) AS "Result"
FROM (
	SELECT
		toInt64(1) AS val	
	UNION ALL
	SELECT
		toInt64(2) AS val) nm
```

При попытке выполнить его и получить значение в таком коде:
```csharp
            using (var connection = new ClickHouseConnection(_settings.ConnectionString))
            {
                connection.Open();
                using (var cmd = connection.CreateCommand())
                {
                    cmd.CommandText =
                        @"SELECT
	                        COUNT(*) AS ""Result""
                        FROM(
                            SELECT
                                toInt64(1) AS val
                            UNION ALL
                            SELECT
                                toInt64(2) AS val) nm";
                    using (var cmdReader = cmd.ExecuteReader())
                    {
                        if (cmdReader.Read())
                        {
                            var someValue = cmdReader.GetInt64(0);
                        }
                    }
                }
            }
```

Возникает исключение:
```
System.InvalidCastException: "Unable to cast object of type 'System.UInt64' to type 'System.Int64'."

```
Аналогично при вызове любых методов для получения числового значений (GetInt32, GetInt16 и др.)

На сколько я вижу, в последней версии был изменен алгоритм преобразования типов. Вместо класса "Convert" теперь используется обычный CAST'инг.

Было:
```csharp
public override long GetInt64(int ordinal) => Convert.ToInt64(GetValue(ordinal), CultureInfo.InvariantCulture);
```
Стало:
```csharp
public override long GetInt64(int ordinal) => (long)GetValue(ordinal);
```

Соответственно, явное преобразование из uint в int64 невозможно, что и приводит к ошибке.

Пока использую обходной путь, используя Convert явно:
```csharp
var someValue= Convert.ToInt64(cmdReader.GetValue(0));
```

Можем вернуть использование Convert для GetInt64?
Возможно аналогично нужно вернуть его использование для всех методов GetInt*, GetDouble, GetDecimal,  GetFloat, т.к. явное преобразование типа возможно только если типы совместимы, а это не всегда так. Сейчас если запрос возвращает тип ULong*, то ни один из методов не может его обработать корректно.

Есть идеи, мысли на этот счет?

**Comment by DarkWanderer** [comment]
Приветствую. 

Для некоторых типов просто нет нормального представления в спецификации ADO [DbDataReader](](https://docs.microsoft.com/en-us/dotnet/api/system.data.common.dbdatareader?view=net-5.0)) - например `IPAddress`, `Tuple`, `UInt64`., это by design. Использование `Convert` в более ранних версиях было необходимым компромиссом - из-за наличия поддержки форматов TSV и JSON, в которых было очень плохо с типизацией. 

В версии 3.0, более строгая типизация была [осознанным изменением](https://github.com/DarkWanderer/ClickHouse.Client/releases/tag/3.0.0.357) - это позволило увеличить производительность на 10-20% в некоторых сценариях в моих тестах. Данное поведение консистентно с другими провайдерами - например [SqlDataReader](https://stackoverflow.com/questions/10119336/datareader-specified-cast-is-not-valid-int32), [OracleDataReader](https://software.databasedevelop.com/article/10399518/Specified+cast+is+not+valid+exception) - вообще, использование cast это скорее правило чем исключение в ADO.NET провайдерах. Конечно, в `SqlDataReader` `SELECT COUNT(*)` возвращает `Int32`, но это скорее неправильно чем правильно (отрицательное количество строк?)

Такие типы UInt64, UInt32 можно получить используя `GetValue`, для этого необязательно использовать специфичные `GetInt64` и т.д.:
```
var someValue1 = Convert.ToInt64(cmdReader.GetValue(0));
var someValue2 = (ulong)cmdReader.GetValue(0);
```
Результатом выражения `COUNT(...)` всегда является `UInt64`:
```
SELECT toTypeName(COUNT(*)) FROM (SELECT 1)
```
```
UInt64
```
Так что исправлением будет либо изменить `reader.GetInt64(i)` на `(ulong)reader.GetValue(i)`, либо исправлением запроса на `SELECT toInt64(COUNT(*)) FROM....`

На мой авторский взгляд в данном случае улучшение производительности перевешивает небольшие неудобства при использовании.
Впрочем, я думаю что могу сделать жизнь проще, добавив методы `GetUInt64`, `GetUInt32` и т.п., чтобы облегчить жизнь "после 3.0"

**Comment by YPermitin** [comment]
Полностью согласен с тем, что возвращать использование Convert в ущерб производительности не стоит.
В своем случае я нашел обходные пути через получение значения как объекта и уже преобразования его к нужному типу.

В будущем, думаю, если будут методы GetUInt64, GetUInt32  и подобные, то это сделает код при использовании библиотеки проще для понимания, но это вопрос не на столько критичный.

Если это поможет, то могу их добавить и отправить PR. Вроде ничего сверхъестественного там не нужно реализовывать. В остальном со всем согласен.

**Comment by YPermitin** [comment]
@DarkWanderer благодарю за https://github.com/DarkWanderer/ClickHouse.Client/commit/fe365d6956fd319a66a1bc81e82d7ba35f87b972

**Comment by DarkWanderer** [comment]
Пока закрою - дополнения выйдут в следующей версии

**Comment by liquehuo** [comment]
use EF Core .  
like `var count = await _clickHouseContext.Order.LongCountAsync();`

got error:
`Unable to cast object of type 'System.UInt64' to type 'System.Int64'.`

only can use cmd and write sql ?

**Comment by DarkWanderer** [comment]
Hi @liquehuo - can you provide a minimal example I can use to reproduce?
