### ISSUE TITLE
Enum8 example

### ISSUE THREAD

**Issue by DmitryDem** [DarkWanderer/ClickHouse.Client#71]
Hi! Could you please provide some example how to insert Enum8 value using parameterized insert?
I have enum8 data type in ClickHouse database:
`Enum8('Sent' = 1, 'Opened' = 2, 'Clicked' = 3)`
And .Net Type
`public enum EventType
    {
        Sent = 0,
        Opened = 1,
        Clicked = 2
    }`

I'm trying insert value using query "INSERT INTO somedb Type VALUES (Type: String)" and passing parameter " command.AddParameter("Type", @event.Type.ToString())" but  get an error "DB::Exception: Cannot parse expression of type Enum8('Sent' = 1, 'Opened' = 2, 'Clicked' = 3) here: Type:String, ..."

**Comment by DarkWanderer** [comment]
Hi,

This is due to strong typing of enum. ClickHouse does not seem to perform correct conversion between types (String=>Enum) in this case.

You can solve this in 3 ways:

1. Specify parameter type explicitly: `INSERT INTO somedb VALUES ({Type:Enum8('Sent' = 1, 'Opened' = 2, 'Clicked' = 3)})`
2. Substitute parameter yourself: `$"INSERT INTO somedb VALUES ('{@event.Type.ToString()}')"`
3. Use `ClickHouseBulkCopy` class for bulk insertion which feeds binary field representation directly into database. This is the best option if you have large amounts of data

**Comment by DmitryDem** [comment]
Thank you!
